package:
    name: {{ environ.get('CONDA_PKG') }}
    version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
    number: {{ environ.get('CONDA_PKG_BUILD', 0) }}

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - argp-standalone # [osx]
        - binutils # [not osx]
        # explicitly list htslib to get same versions of
        # other things, even when we build our own. When
        # using bioconda htslib the other things can be
        # removed from here. The pin is because we copy
        # private interface code for hts_base_mod_state
        # so need to ensure compatibility. We should
        # hopefully be fine with ABI
        - bioconda::htslib==1.16
          # - libcurl
          # - bzip2
          # - xz
          # - zlib
          # - libdeflate
          # - openssl  # [not osx]
    run:
        - bioconda::htslib==1.16
          # - libcurl
          # - bzip2
          # - xz
          # - zlib
          # - libdeflate
          # - openssl  # [not osx]

test:
    commands:
        - modbam2bed --help

about:
    home: "https://github.com/epi2me-labs/modbam2bed"
    license: Mozilla Public License 2.0 
    license_family: OTHER
    license_file: LICENSE
    summary: "Summarise BAM files containing modified-base information to bedMethyl format."
    doc_url: https://github.com/epi2me-labs/modbam2bed
    dev_url: https://github.com/epi2me-labs/modbam2bed

extra:
    recipe-maintainers:
        - cjw85
